Ext.define('OsakaTest.store.Genderes',{
    extend:'Ext.data.Store',
    autoLoad:true,
    fields:['genderid','jpgender'],
    data:[
        {"genderid":0,"jpgender":"男"},
        {"genderid":1,"jpgender":"女"}
    ]
});
