Ext.define('OsakaTest.view.Grid',{
    extend:'Ext.grid.Panel',
    alias:'widget.osakatestgrid',
    title:'名簿',
    store:'Employees',
    columns:[
        {text:'名前',dataIndex:'name'},
        {text:'ふりがな',dataIndex:'kana'},
        {text:'メールアドレス',dataIndex:'address'},
        {text:'性別',dataIndex:'jpgender'},
        {text:'生年月日',dataIndex:'birthday'},
        {text:'県',dataIndex:'pref'},
        {text:'携帯電話番号',dataIndex:'mobile_phone'}
    ]
});
